spring:
  application:
    name: places
  cloud:
    discovery:
      enabled: false
  datasource:
    initialization-mode: always

weather:
  service:
    address: http://localhost:8089

---
spring:
  profiles: cloud
  cloud:
    discovery:
      enabled: true
    services:
      registrationMethod: direct

weather:
  service:
    address: //weather
