spring:
  application:
    name: places
  cloud:
    discovery:
      enabled: false
  datasource:
    initialization-mode: always

---
spring:
  profiles: cloud
  cloud:
    discovery:
      enabled: true
    services:
      registrationMethod: direct
    loadbalancer:
      ribbon:
        enabled: false
